# Generated by Django 4.0.3 on 2022-04-15 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=4)),
                ('truename', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('state', models.IntegerField(default=0)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(db_column='create_data', default=datetime.datetime(2022, 4, 15, 11, 2, 38, 922873))),
                ('updateDate', models.DateTimeField(db_column='update_data', null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
