# Generated by Django 3.2.2 on 2022-05-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_user_createdate_alter_user_updatedate_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aclValue', models.CharField(db_column='acl_value', max_length=20)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=20)),
                ('module', models.ForeignKey(db_column='module_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.module')),
            ],
            options={
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(db_column='role_name', max_length=20)),
                ('roleRemark', models.CharField(db_column='role_remark', max_length=120)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(db_column='update_date', max_length=20)),
                ('permissions', models.ManyToManyField(through='system.Permission', to='system.Module')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=20)),
                ('role', models.ForeignKey(db_column='role_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.role')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.user')),
            ],
            options={
                'db_table': 't_user_role',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(db_column='role_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='system.UserRole', to='system.Role'),
        ),
    ]
